import pandas as pd
class AnalyticsEngine:
    """
    Computes business KPIs and analytics
    from the engineered retail dataset.
    """

    @staticmethod
    def generate(df):

        return {
            "kpis": AnalyticsEngine.compute_kpis(df),

            "monthly_sales": AnalyticsEngine.monthly_sales(df),

            "country_sales": AnalyticsEngine.country_sales(df),

            "top_products_by_revenue": AnalyticsEngine.top_products_by_revenue(df),

            "top_products_by_quantity": AnalyticsEngine.top_products_by_quantity(df),

            "top_customers_by_revenue": AnalyticsEngine.top_customers_by_revenue(df),
            
            "top_customers_by_orders": AnalyticsEngine.top_customers_by_orders(df),

            "rfm_summary": AnalyticsEngine.compute_rfm(df),

            "daily_sales": AnalyticsEngine.daily_sales(df),

            "weekly_sales": AnalyticsEngine.weekly_sales(df),

            "quarterly_sales": AnalyticsEngine.quarterly_sales(df),

            "monthly_growth": AnalyticsEngine.monthly_growth(df),

            "sales_summary": AnalyticsEngine.sales_summary(df),

            "daily_summary": AnalyticsEngine.daily_summary(df),

            "average_daily_revenue": AnalyticsEngine.average_daily_revenue(df),
        }

    @staticmethod
    def compute_kpis(df):
        """
        Compute high-level business KPIs.
        """

        total_revenue = df["Revenue"].sum()

        total_orders = df["Invoice"].nunique()

        total_customers = df["CustomerID"].nunique()

        total_products = df["Product"].nunique()

        average_order_value = (
            total_revenue / total_orders
            if total_orders
            else 0
        )

        return {

            "total_revenue": float(round(total_revenue, 2)),

            "total_orders": int(total_orders),

            "total_customers": int(total_customers),

            "total_products": int(total_products),

            "average_order_value": float(round(
                average_order_value,
                2
            ))

        }

    @staticmethod
    def monthly_sales(df):
        """
            Compute monthly revenue
        """
        monthly = (
            df.groupby("Month")["Revenue"].sum().sort_index()
        )
        return {
            int(month): float(round(revenue, 2))
            for month, revenue in monthly.items()
        }

    @staticmethod
    def country_sales(df):
        """
        Compute revenue generated by each country.
        """

        country = (
            df.groupby("Country")["Revenue"]
            .sum()
            .sort_values(ascending=False)
        )

        return {
            country_name: float(round(revenue, 2))
            for country_name, revenue in country.items()
        }

    @staticmethod
    def top_products_by_revenue(df, top_n=10):
        """
        Return top N products based on revenue.
        """

        products = (
            df.groupby("Product")["Revenue"]
            .sum()
            .sort_values(ascending=False)
            .head(top_n)
        )

        return {
            product: float(round(revenue, 2))
            for product, revenue in products.items()
        }

    @staticmethod
    def top_products_by_quantity(df, top_n=10):
        """
        Return top N products based on quantity sold.
        """

        products = (
            df.groupby("Product")["Quantity"]
            .sum()
            .sort_values(ascending=False)
            .head(top_n)
        )

        return {
            product: int(quantity)
            for product, quantity in products.items()
        }

    @staticmethod
    def top_customers_by_revenue(df, top_n=10):
        """
        Return top N customers based on total revenue.
        """

        customers = (
            df.dropna(subset=["CustomerID"])
            .groupby("CustomerID")["Revenue"]
            .sum()
            .sort_values(ascending=False)
            .head(top_n)
        )

        return {
            str(int(customer_id)): float(round(revenue, 2))
            for customer_id, revenue in customers.items()
        }

    @staticmethod
    def top_customers_by_orders(df, top_n=10):
        """
        Return top N customers based on number of unique orders.
        """

        customers = (
            df.dropna(subset=["CustomerID"])
            .groupby("CustomerID")["Invoice"]
            .nunique()
            .sort_values(ascending=False)
            .head(top_n)
        )

        return {
            str(int(customer_id)): int(orders)
            for customer_id, orders in customers.items()
        }

    @staticmethod
    def compute_rfm(df):
        """
        Compute RFM metrics for every customer.
        """

        customer_df = df.dropna(subset=["CustomerID"]).copy()

        snapshot_date = customer_df["InvoiceDate"].max() + pd.Timedelta(days=1)

        rfm = (
            customer_df
            .groupby("CustomerID")
            .agg({
                "InvoiceDate": lambda x: (snapshot_date - x.max()).days,
                "Invoice": "nunique",
                "Revenue": "sum"
            })
            .reset_index()
        )

        rfm.columns = [
            "CustomerID",
            "Recency",
            "Frequency",
            "Monetary"
        ]

        rfm["R_Score"] = pd.qcut(
            rfm["Recency"],
            q = 5,
            labels = [5, 4, 3, 2, 1]
        )

        rfm["F_Score"] = pd.qcut(
            rfm["Frequency"].rank(method="first"),
            q = 5,
            labels = [1, 2, 3, 4, 5]
        )
        rfm["M_Score"] = pd.qcut(
            rfm["Monetary"].rank(method="first"),
            q = 5,
            labels = [1, 2, 3, 4, 5]
        )

        rfm["RFM_Score"] = (
            rfm["R_Score"].astype(str) + 
            rfm["F_Score"].astype(str) + 
            rfm["M_Score"].astype(str)  
        )

        def get_segment(score):
            r = int(score[0])
            f = int(score[1])
            m = int(score[2])

            # Champion
            if r >= 4 and f >= 4 and m >= 4:
                return "Champion"

            # Loyal Customer
            elif r >= 3 and f >= 3 and m >= 3:
                return "Loyal Customer"

            # Potential Loyalists
            elif r >= 3:
                return "Potential Loyalists"

            # at risk
            elif f >= 3 or m >= 3:
                return "At Risk"

            else:
                return "Lost Customer"

        rfm["Segment"] = rfm["RFM_Score"].apply(get_segment)

        segment_summary = (
            rfm["Segment"].value_counts().to_dict()
        )
    

        return {
            "rfm_table": rfm,
            "segment_summary": segment_summary
        }

    @staticmethod
    def daily_sales(df):
        """
        Compute daily revenue.
        """

        daily = (
            df.groupby(df["InvoiceDate"].dt.date)["Revenue"]
            .sum()
            .sort_index()
        )

        return {
            str(date): float(round(revenue, 2))
            for date, revenue in daily.items()
        }

    @staticmethod
    def weekly_sales(df):
        """
        Compute weekly revenue.
        """

        weekly = (
            df.groupby(df["InvoiceDate"].dt.isocalendar().week)["Revenue"]
            .sum()
            .sort_index()
        )

        return {
            int(week): float(round(revenue, 2))
            for week, revenue in weekly.items()
        }

    @staticmethod
    def quarterly_sales(df):
        """
        Compute quarterly revenue.
        """

        quarterly = (
            df.groupby("Quarter")["Revenue"]
            .sum()
            .sort_index()
        )

        return {
            int(quarter): float(round(revenue, 2))
            for quarter, revenue in quarterly.items()
        }

    @staticmethod
    def monthly_growth(df):
        """
        Compute Month-over-Month (MoM) revenue growth.
        """

        monthly = (
            df.groupby("Month")["Revenue"]
            .sum()
            .sort_index()
        )

        growth = monthly.pct_change() * 100

        growth = growth.fillna(0)

        return {
            int(month): float(round(rate, 2))
            for month, rate in growth.items()
        }

    @staticmethod
    def sales_summary(df):
        """
        Compute high-level sales insights.
        """

        monthly = (
            df.groupby("Month")["Revenue"]
            .sum()
            .sort_index()
        )

        best_month = monthly.idxmax()
        worst_month = monthly.idxmin()

        return {

            "best_month": int(best_month),

            "best_month_revenue": float(round(monthly.max(), 2)),

            "worst_month": int(worst_month),

            "worst_month_revenue": float(round(monthly.min(), 2))

        }

    @staticmethod
    def daily_summary(df):
        """
        Compute best and worst sales day.
        """

        daily = (
            df.groupby(df["InvoiceDate"].dt.date)["Revenue"]
            .sum()
        )

        best_day = daily.idxmax()
        worst_day = daily.idxmin()

        return {

            "best_day": str(best_day),

            "best_day_revenue": float(round(daily.max(), 2)),

            "worst_day": str(worst_day),

            "worst_day_revenue": float(round(daily.min(), 2))

        }

    @staticmethod
    def average_daily_revenue(df):
        """
        Compute average revenue per day.
        """

        daily = (
            df.groupby(df["InvoiceDate"].dt.date)["Revenue"]
            .sum()
        )

        return float(round(daily.mean(), 2))